// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// VarSelH
List VarSelH(NumericVector a, int n, int p, int q, int qstar, int MaxIt);
RcppExport SEXP qVarSel_VarSelH(SEXP aSEXP, SEXP nSEXP, SEXP pSEXP, SEXP qSEXP, SEXP qstarSEXP, SEXP MaxItSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< int >::type p(pSEXP );
        Rcpp::traits::input_parameter< int >::type q(qSEXP );
        Rcpp::traits::input_parameter< int >::type qstar(qstarSEXP );
        Rcpp::traits::input_parameter< int >::type MaxIt(MaxItSEXP );
        List __result = VarSelH(a, n, p, q, qstar, MaxIt);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
